server: 
  port: ${PORT:9193}
  
spring:  application:
    name: product-api
    
  main: 
    allow-circular-references: true
    
  datasource:     driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/product-db
    username: postgres
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
    plataform: postgresql
    maxActive: 3      
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

app-config:
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}